name: clim680-xesmf
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab=1.2.5
  - jupyter_client=5.3.1
  - nbserverproxy
  - netcdf4
  - metpy
  - numpy
  - climpred
  - cfgrib
  - scipy
  - xarray
  - dask
  - xskillscore
  - cartopy
  - matplotlib
  - tqdm
  - ipywidgets
  - eofs 
  - hvplot
  - esmpy
  - xesmf=0.3.0
  - boto3
  - botocore
  - intake
  - intake-esm
  - gcsfs
